FAIL
run: open "deleteme": FAILED
